### ISSUE TITLE
Empty training data was given. You'll need more than one sample to learn a model. in function 'cv::face::LBPH::train'

### ISSUE THREAD

**Issue by KhomZ** [KhomZ/Facial-Recognition-Based-Student-Attendance-System#3]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "c:\Users\ACER\Desktop\myProj\Facial-Recognition-Based-Student-Attendance-System\train.py", line 176, in train_classifier   
    clf.train(faces,ids)
cv2.error: OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-1i5nllza\opencv_contrib\modules\face\src\lbph_faces.cpp:362: error: (-210:Unsupported format or combination of formats) Empty training data was given. You'll need more than one sample to learn a model. in function 'cv::face::LBPH::train'

Exception in Tkinter callback
Traceback (most recent call last):
encv_contrib\modules\face\src\lbph_faces.cpp:362: error: (-210:Unsupported format or combination of formats) Empty training data was given. You'll need more than one sample to learn a model. in function 'cv::face::LBPH::train'

**Comment by KhomZ** [comment]
This is the issue that's getting on my nerves!!!!!
