### ISSUE TITLE
Exception in Tkinter callback

### ISSUE THREAD

**Issue by KhomZ** [KhomZ/Facial-Recognition-Based-Student-Attendance-System#5]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "c:\Users\ACER\Desktop\myProj\Facial-Recognition-Based-Student-Attendance-System\face_recognition.py", line 188, in face_recog     
    img=recognize(img,clf,faceCascade)
  File "c:\Users\ACER\Desktop\myProj\Facial-Recognition-Based-Student-Attendance-System\face_recognition.py", line 177, in recognize      
    coord=draw_boundray(img,faceCascade,1.1,10,(255,25,255),"Face",clf)
  File "c:\Users\ACER\Desktop\myProj\Facial-Recognition-Based-Student-Attendance-System\face_recognition.py", line 165, in draw_boundray  
    self.mark_attendance(i,r,n,d)
  File "c:\Users\ACER\Desktop\myProj\Facial-Recognition-Based-Student-Attendance-System\face_recognition.py", line 76, in mark_attendance 
    with open("Teamkyzen23.csv","r+",newline="\n") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Teamkyzen23.csv'
[ WARN:1] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-1i5nllza\opencv\modules\videoio\src\cap_msmf.cpp (376) `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): OnReadSample() is called with error status: -1072873821
[ WARN:1] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-1i5nllza\opencv\modules\videoio\src\cap_msmf.cpp (388) `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): async ReadSample() call is failed with error status: -1072873821
Exception in Tkinter callback
[ WARN:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-1i5nllza\opencv\modules\videoio\src\cap_msmf.cpp (438) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback
Traceback (most recent call last):
  File "C:\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "c:\Users\ACER\Desktop\myProj\Facial-Recognition-Based-Student-Attendance-System\face_recognition.py", line 188, in face_recog     
    img=recognize(img,clf,faceCascade)
  File "c:\Users\ACER\Desktop\myProj\Facial-Recognition-Based-Student-Attendance-System\face_recognition.py", line 177, in recognize      
    coord=draw_boundray(img,faceCascade,1.1,10,(255,25,255),"Face",clf)
  File "c:\Users\ACER\Desktop\myProj\Facial-Recognition-Based-Student-Attendance-System\face_recognition.py", line 165, in draw_boundray  
    self.mark_attendance(i,r,n,d)
  File "c:\Users\ACER\Desktop\myProj\Facial-Recognition-Based-Student-Attendance-System\face_recognition.py", line 76, in mark_attendance 
    with open("Teamkyzen23.csv","r+",newline="\n") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Teamkyzen23.csv'
[ WARN:2] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-1i5nllza\opencv\modules\videoio\src\cap_msmf.cpp (376) `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): OnReadSample() is called with error status: -1072873821
[ WARN:2] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-1i5nllza\opencv\modules\videoio\src\cap_msmf.cpp (388) `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): async ReadSample() call is failed with error status: -1072873821
Exception in Tkinter callback
[ WARN:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-1i5nllza\opencv\modules\videoio\src\cap_msmf.cpp (438) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback
Traceback (most recent call last):
  File "C:\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "c:\Users\ACER\Desktop\myProj\Facial-Recognition-Based-Student-Attendance-System\face_recognition.py", line 188, in face_recog
    img=recognize(img,clf,faceCascade)
  File "c:\Users\ACER\Desktop\myProj\Facial-Recognition-Based-Student-Attendance-System\face_recognition.py", line 177, in recognize      
    coord=draw_boundray(img,faceCascade,1.1,10,(255,25,255),"Face",clf)
  File "c:\Users\ACER\Desktop\myProj\Facial-Recognition-Based-Student-Attendance-System\face_recognition.py", line 165, in draw_boundray  
    self.mark_attendance(i,r,n,d)
  File "c:\Users\ACER\Desktop\myProj\Facial-Recognition-Based-Student-Attendance-System\face_recognition.py", line 76, in mark_attendance 
    with open("Teamkyzen23.csv","r+",newline="\n") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Teamkyzen23.csv'
[ WARN:1] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-1i5nllza\opencv\modules\videoio\src\cap_msmf.cpp (376) `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): OnReadSample() is called with error status: -1072873821
[ WARN:1] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-1i5nllza\opencv\modules\videoio\src\cap_msmf.cpp (388) `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): async ReadSample() call is failed with error status: -1072873821
Exception in Tkinter callback
[ WARN:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-1i5nllza\opencv\modules\videoio\src\cap_msmf.cpp (438) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback
Traceback (most recent call last):
  File "C:\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "c:\Users\ACER\Desktop\myProj\Facial-Recognition-Based-Student-Attendance-System\face_recognition.py", line 188, in face_recog     
    img=recognize(img,clf,faceCascade)
  File "c:\Users\ACER\Desktop\myProj\Facial-Recognition-Based-Student-Attendance-System\face_recognition.py", line 177, in recognize      
    coord=draw_boundray(img,faceCascade,1.1,10,(255,25,255),"Face",clf)
  File "c:\Users\ACER\Desktop\myProj\Facial-Recognition-Based-Student-Attendance-System\face_recognition.py", line 165, in draw_boundray  
    self.mark_attendance(i,r,n,d)
  File "c:\Users\ACER\Desktop\myProj\Facial-Recognition-Based-Student-Attendance-System\face_recognition.py", line 76, in mark_attendance 
    with open("Teamkyzen23.csv","r+",newline="\n") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Teamkyzen23.csv'
[ WARN:1] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-1i5nllza\opencv\modules\videoio\src\cap_msmf.cpp (376) `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): OnReadSample() is called with error status: -1072873821
[ WARN:1] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-1i5nllza\opencv\modules\videoio\src\cap_msmf.cpp (388) `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): async ReadSample() call is failed with error status: -1072873821
Exception in Tkinter callback
[ WARN:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-1i5nllza\opencv\modules\videoio\src\cap_msmf.cpp (438) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback
Traceback (most recent call last):
  File "C:\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "c:\Users\ACER\Desktop\myProj\Facial-Recognition-Based-Student-Attendance-System\face_recognition.py", line 188, in face_recog     
    img=recognize(img,clf,faceCascade)
  File "c:\Users\ACER\Desktop\myProj\Facial-Recognition-Based-Student-Attendance-System\face_recognition.py", line 177, in recognize      
    coord=draw_boundray(img,faceCascade,1.1,10,(255,25,255),"Face",clf)
  File "c:\Users\ACER\Desktop\myProj\Facial-Recognition-Based-Student-Attendance-System\face_recognition.py", line 165, in draw_boundray  
    self.mark_attendance(i,r,n,d)
  File "c:\Users\ACER\Desktop\myProj\Facial-Recognition-Based-Student-Attendance-System\face_recognition.py", line 76, in mark_attendanc      with open("Teamkyzen23.csv","r+",newline="\n") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Teamkyzen23.csv'[ WARN:3] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-1i5nllza\opencv\modules\videoio\src\cap_msmf.cpp (438) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback

**Comment by KhomZ** [comment]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "c:\Users\ACER\Desktop\myProj\Facial-Recognition-Based-Student-Attendance-System\face_recognize.py", line 569, in Face_reco        
    cv2.imshow("Welcome To Face Recognition",img)
cv2.error: OpenCV(4.5.3) :-1: error: (-5:Bad argument) in function 'imshow'
> Overload resolution failed:
>  - mat is not a numpy array, neither a scalar
>  - Expected Ptr<cv::cuda::GpuMat> for argument 'mat'
>  - Expected Ptr<cv::UMat> for argument 'mat'

[ WARN:1] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-1i5nllza\opencv\modules\videoio\src\cap_msmf.cpp (438) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback

**Comment by KhomZ** [comment]
🥇 
🔡
🔢
👺
