### ISSUE TITLE
Exception in Tkinter callback Traceback (most recent call last):     img=recognize(img,clf,faceCascade)   File "c:\Users\ACER\Desktop\myProj\Facial-Recognition-Based-Student-Attendance-System\face_recognition.py", line 179, in recognize           coord=draw_boundray(img,faceCascade,1.1,10,(255,25,255),"Face",clf)   File "c:\Users\ACER\Desktop\myProj\Facial-Recognition-Based-Student-Attendance-System\face_recognition.py", line 167, in draw_boundray       self.mark_attendance(i,r,n,d) TypeError: mark_attendance() takes 4 positional arguments but 5 were given [ WARN:1] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-1i5nllza\opencv\modules\videoio\src\cap_msmf.cpp (438) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback

### ISSUE THREAD

**Issue by KhomZ** [KhomZ/Facial-Recognition-Based-Student-Attendance-System#6]
Exception in Tkinter callback
Traceback (most recent call last):
    img=recognize(img,clf,faceCascade)
  File "c:\Users\ACER\Desktop\myProj\Facial-Recognition-Based-Student-Attendance-System\face_recognition.py", line 179, in recognize      
    coord=draw_boundray(img,faceCascade,1.1,10,(255,25,255),"Face",clf)
  File "c:\Users\ACER\Desktop\myProj\Facial-Recognition-Based-Student-Attendance-System\face_recognition.py", line 167, in draw_boundray  
    self.mark_attendance(i,r,n,d)
TypeError: mark_attendance() takes 4 positional arguments but 5 were given
[ WARN:1] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-1i5nllza\opencv\modules\videoio\src\cap_msmf.cpp (438) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback

**Comment by KhomZ** [comment]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
    img=recognize(img,clf,faceCascade)
  File "c:\Users\ACER\Desktop\myProj\Facial-Recognition-Based-Student-Attendance-System\face_recognition.py", line 179, in recognize
    coord=draw_boundray(img,faceCascade,1.1,10,(255,25,255),"Face",clf)
  File "c:\Users\ACER\Desktop\myProj\Facial-Recognition-Based-Student-Attendance-System\face_recognition.py", line 167, in draw_boundray
    self.mark_attendance(self,i,r,n,d)
TypeError: mark_attendance() takes 5 positional arguments but 6 were given
[ WARN:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-1i5nllza\opencv\modules\videoio\src\cap_msmf.cpp (438) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback

**Comment by KhomZ** [comment]
@KhomZ
